version: '3.8'

services:
  bot:
    build: .
    container_name: svoy_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python bot.py

  admin:
    build: .
    container_name: svoy_admin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5005:5005"
    volumes:
      - ./data:/app/data
    command: python admin_panel.py
